language: go
go:
  - 1.7.x
  - 1.8.x
before_install:
  - go get github.com/axw/gocov/gocov
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
  - go get -t -v ./...

script:
  - go test -v ./ping
  - ./codecov.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
