language: go
go:
  - tip
before_install:
  - go get github.com/axw/gocov/gocov
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
script:
  - go test -v ./ping
